#### TOBIG'S 14기 정규세션 4주차 SVM 
### ASSIGNMENT1. Multiclass SVM 구현

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn import metrics

#IRIS 데이터 로드
iris =  sns.load_dataset('iris') 
X= iris.iloc[:,:4] #학습할데이터
y = iris.iloc[:,-1] #타겟
print(y)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object


In [2]:
# One VS Rest 구현을 위해 1) class가 0 or not 2)class가 1 or not을 구분하기 위한 머신 등을 미리 만들어주자
svm_1 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_2 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_3 = SVC(kernel ='rbf', C = 5, gamma = 5)

In [3]:
from sklearn.model_selection import train_test_split #test/train 데이터로 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)

In [4]:
scaler = StandardScaler() #scaling
X_train = scaler.fit_transform(X_train) 
X_test = scaler.transform(X_test)

In [5]:
y_train = pd.get_dummies(y_train) #one hot encoding

In [6]:
svm_1.fit(X_train,y_train.iloc[:,0]) # 데이터 클레스가 0 or not 구분해주는 머신
svm_2.fit(X_train,y_train.iloc[:,1]) # 데이터 클레스가 1 or not 구분해주는 머신
svm_3.fit(X_train,y_train.iloc[:,2]) # 데이터 클레스가 2 or not 구분해주는 
print(svm_1.predict(X_test)) #데이터 클래스가 0 or not을 구분해주는 애를 통해서 테스트 데이터의 클래스가 0인지, 0이 아닌인지 예측해보자

print(svm_1.decision_function(X_test)) #decision_function hyperplane과의 거리를 구하는 방법(필요하다면 활용해주세요!)

[0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0]
[-1.12359969 -0.86782512 -0.65599247 -0.50194294 -0.76541147 -0.8819188
  1.07735938 -0.99156769  0.50201986 -0.9984315  -0.84532712  0.17062549
  0.34917127 -0.9813287  -0.72783399 -0.93313988  1.28153212 -0.56827872
 -0.73092732 -0.99670034  0.43553308 -0.96967771 -0.83939495 -1.03305682
 -0.75566609  1.13888006  0.42965012 -1.04268452 -0.93608147 -1.06090982]


In [7]:
# 부호가 모든 같은 경우가 있는가? > 모두 동점인 경우가 생길 것
for i in range(len(X_test)):
    # ~. decision_function을 이용하면 해당 데이터가 하이퍼플레인으로부터 얼마나 떨어져있는지 '거리'가 나온다!
    # 다음은 그 값의 부호를 이용해 모두가 동점인 경우가 있는지 출력하는 함수 
    if (np.sign(svm_1.decision_function(X_test)[i]) == np.sign(svm_2.decision_function(X_test)[i]))\
    and (np.sign(svm_2.decision_function(X_test)[i]) == np.sign(svm_3.decision_function(X_test)[i])):
        print(i)

3
17
18


* 멘토링에서 많은 도움을 받았습니다!

In [104]:
## Case 1 : One vs Rest SVM을 이부분에 구현해주세요 위 결과들을 이용해서 multi class SVM을 직접 구현해주세요! 하드코딩이 하시기 편할겁니다.

In [8]:
#예측값을 저장하기위해 0으로 구성된 vote를 만들어준다.
vote = np.zeros((len(X_test),3))
for i in range(len(X_test)): 
    if svm_1.predict(X_test)[i] == 1: #setosa이면 1을 주고 나머지는 -1
        vote[i][0] += 1
        vote[i][1] -= 1
        vote[i][2] -= 1
    elif svm_2.predict(X_test)[i] == 1 : #versicolor이면 1을 주고 나머지는 -1
        vote[i][0] -= 1
        vote[i][1] += 1
        vote[i][2] -= 1
    elif svm_3.predict(X_test)[i] == 1 :#virginica이면 1을 주고 나머지는 -1
        vote[i][0] -= 1
        vote[i][1] -= 1
        vote[i][2] += 1

In [9]:
vote

array([[-1.,  1., -1.],
       [-1.,  1., -1.],
       [-1.,  1., -1.],
       [ 0.,  0.,  0.],
       [-1., -1.,  1.],
       [-1., -1.,  1.],
       [ 1., -1., -1.],
       [-1., -1.,  1.],
       [ 1., -1., -1.],
       [-1.,  1., -1.],
       [-1., -1.,  1.],
       [ 1., -1., -1.],
       [ 1., -1., -1.],
       [-1., -1.,  1.],
       [-1.,  1., -1.],
       [-1.,  1., -1.],
       [ 1., -1., -1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [-1., -1.,  1.],
       [ 1., -1., -1.],
       [-1., -1.,  1.],
       [-1.,  1., -1.],
       [-1.,  1., -1.],
       [-1., -1.,  1.],
       [ 1., -1., -1.],
       [ 1., -1., -1.],
       [-1., -1.,  1.],
       [-1., -1.,  1.],
       [-1.,  1., -1.]])

* 값이 다 0일때를 해결해주어여한다!
* 가장많이 나온 값으로 대체해줄것이다.

In [10]:
#vote값이 1인 인덱스 번호를 뽑는다.
labels = [np.where(args == 1)[0] for args in vote]

In [11]:
labels

[array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([0], dtype=int64),
 array([2], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([2], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([2], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([], dtype=int64),
 array([], dtype=int64),
 array([2], dtype=int64),
 array([0], dtype=int64),
 array([2], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([2], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([2], dtype=int64),
 array([2], dtype=int64),
 array([1], dtype=int64)]

In [12]:
#가장많이 나온값이 2이다. 이값으로 0인값을 대체해줄것이다.
pd.Series(labels).value_counts()

[2]    10
[1]     9
[0]     8
[]      1
[]      1
[]      1
dtype: int64

In [13]:
#0인값을 가장많은 값으로 대체해주고, 0,1,2 값을 다시 원래값으로 바꿔준다.
pred = []
for l in labels:
    if len(l) == 0: 
        v = 'versicolor'
    elif l[0] == 1:
        v = 'versicolor'
    elif l[0] == 0:
        v = 'setosa'
    elif l[0] == 2:
        v = 'virginica'
    pred.append(v)

In [14]:
## Case 1 : One vs Rest SVM을 이부분에 구현해주세요 위 결과들을 이용해서 multi class SVM을 직접 구현해주세요! 하드코딩이 하시기 편할겁니다.
(sum(y_test.values == pred) / len(pred)) #예측값과 실제값이 같은것만 개수를 세줘서 전체 길이로 나눠서 accuracy를 구했다. 

0.9

In [ ]:
## Case 1 : One vs Rest SVM을 이부분에 구현해주세요 위 결과들을 이용해서 multi class SVM을 직접 구현해주세요! 하드코딩이 하시기 편할겁니다.
#정답

['versicolor', 'versicolor', 'versicolor', 'virginica', 'virginica', 'virginica', 'setosa', 'virginica', 'setosa', 'versicolor', 'virginica', 'setosa', 'setosa', 'virginica', 'versicolor', 'versicolor', 'setosa', 'versicolor', 'virginica', 'virginica', 'setosa', 'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa', 'setosa', 'virginica', 'virginica', 'versicolor']


0.8666666666666667

In [15]:
# 원래 라이브러리가 제공하는 multi class SVM과 여러분이 구현한 multiclass SVM 결과를 비교해주세요
from sklearn.model_selection import train_test_split #데이터셋 분리
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X, y, test_size=0.2, random_state=48)

svm_4 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_4.fit(X_train_2, y_train_2)
y_pred = svm_4.predict(X_test_2)

metrics.accuracy_score(y_test_2,y_pred)

0.8666666666666667

* 3개의 분류기로 이용하여 구현한 svm의 정확도가 0.9이고 하나의 분류기만을 이용한 svm은 정확도가 0.8333333333333334인것을 보니 3개의 분류기를 사용한것이 더 좋은 성능을 보이는 것을 알 수 있다. 